# Generated by Django 3.2.9 on 2021-11-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20211109_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='crated_by',
            new_name='created_by',
        ),
    ]
