# Generated by Django 3.2.9 on 2021-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'company')},
        ),
    ]
