# Generated by Django 3.2.9 on 2021-11-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20211112_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='display_id',
            field=models.IntegerField(default=1),
        ),
    ]
