# Generated by Django 3.2.9 on 2021-11-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_ticket_display_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-display_id'], name='ticketing_t_display_691d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['-display_id'], name='ticketing_u_display_2cd43c_idx'),
        ),
    ]
